// src/codegen/template.ts - deterministic Rust source generator for the OZ
// `Policy` escape-hatch skeleton.
//
// SUPERSEDED. The architecture this belongs to no longer exists. A deployed
// policy involves exactly two contracts, the OZ smart account and one
// immutable interpreter, and the synthesiser emits policy DATA rather than
// code. Nothing on the synthesis path reaches this module, and no install can
// produce a contract from it. When a constraint falls outside the grammar the
// answer is to version the synthesiser and the interpreter together, not to
// put unaudited Rust on chain per policy.
//
// Deleting it is a decision nobody has taken yet, not a dependency question.
// `compile-gate.ts` takes a Rust string and knows nothing about this module,
// and its tests compile a hardcoded fixture, so the gate keeps working either
// way. What deleting this would remove is the only in-repo producer of policy
// Rust for the gate to check. Do not read its presence as the product
// generating contracts, and do not wire it into the synthesis path.
//
// What follows describes the abandoned design.
//
// This is the LAST-RESORT tool for constraints the v1 DSL cannot express. It
// lives OUT of the audited happy-path surface; the synthesiser never emits it
// automatically. It mirrors Zodiac Roles' `Custom` operator: a hand-written
// (here: scaffolded) policy the operator assumes responsibility for.
//
// The skeleton carries five storage invariants the user MUST preserve when
// filling in the predicate logic:
//   1. `smart_account.require_auth()` is invoked INSIDE `enforce`.
//   2. Storage is keyed by the composite `(smart_account, rule_id)`.
//   3. Chain reads use `unwrap_or_default()` so a missing key is a permitted
//      default, not a panic.
//   4. Storage is `persistent()` (NOT `instance()`) so the policy survives
//      contract instance lifecycle changes.
//   5. `uninstall` removes the stored state.
//
// Determinism: same `(spec, name)` -> byte-identical output. No clock, no RNG,
// no environment reads.

/** A small typed description of one uncovered constraint the v1 DSL refused
 *  to express. The synthesiser surfaces these from `CompileResult.uncovered`
 *  and the codegen escape hatch wraps them into a hand-auditable skeleton. */
export interface EscapeHatchSpec {
  /** Address of the policy contract the skeleton is generated for. */
  contract: string
  /** The trait method the predicate lives inside (default: 'enforce'). */
  fnName?: string
  /** Human-readable description of each construct the DSL could not cover. */
  uncovered: string[]
}

/** Format a name for use as a Rust identifier. The input is constrained by
 *  the caller (a kebab-case policy name + alphanumeric addresses); this is a
 *  belt-and-braces sanitiser that maps anything non-identifier to '_'. */
function asRustIdent(s: string): string {
  let out = ''
  for (let i = 0; i < s.length; i++) {
    const ch = s.charCodeAt(i)
    const ok =
      (ch >= 48 && ch <= 57) || // 0-9
      (ch >= 65 && ch <= 90) || // A-Z
      (ch >= 97 && ch <= 122) || // a-z
      ch === 95 // _
    out += ok ? s[i] : '_'
  }
  // Identifiers may not start with a digit.
  if (out.length > 0 && out.charCodeAt(0) >= 48 && out.charCodeAt(0) <= 57) {
    out = `_${out}`
  }
  return out || 'policy'
}

/** Render the `uncovered` list as a `//` comment block (one line per item). */
function renderUncovered(uncovered: string[]): string {
  if (uncovered.length === 0) {
    return '    // (no specific uncovered constructs reported)'
  }
  return uncovered.map((line) => `    // - ${line}`).join('\n')
}

/** Generate a deterministic OZ `Policy` skeleton for an uncovered constraint.
 *
 *  The skeleton is NOT a finished policy; the user fills in the predicate
 *  logic in the marked TODO(user) holes and audits the result themselves.
 *
 *  Same `(spec, name)` always produces byte-identical output. */
export function generateRust(spec: EscapeHatchSpec, name: string): string {
  const _contract = spec.contract
  const _fnName = spec.fnName ?? 'enforce'
  const structName = asRustIdent(name)
  const _dataKeyName = `${asRustIdent(name)}_data`
  const uncoveredBlock = renderUncovered(spec.uncovered)

  return `// Auto-generated by the OZ Policy Builder codegen escape hatch.
// THIS OUTPUT IS THE USER'S TO COMPLETE AND AUDIT.
// The synthesiser never emits it on the happy path; reach for it only when
// a constraint cannot be expressed in the v1 DSL grammar (same shape as
// Zodiac Roles' \`Custom\` operator).

#![no_std]

use soroban_sdk::{contract, contractimpl, contracttype, Address, Env, Vec};

#[contracttype]
pub enum DataKey {
    /// Composite key \`(smart_account, rule_id)\` so multiple policies on
    /// one smart account coexist without collision.
    State(Address, u32),
}

#[contract]
pub struct ${structName};

#[contractimpl]
impl ${structName} {
    pub fn install(e: &Env, smart_account: Address, rule_id: u32) {
        // TODO(user): initialise policy state for this (smart_account, rule_id).
        // The skeleton leaves the stored value empty; the predicate body
        // (in \`enforce\`) decides what to read.
        e.storage().persistent().set(
            &DataKey::State(smart_account.clone(), rule_id),
            &(),
        );
    }

    pub fn enforce(
        e: &Env,
        smart_account: Address,
        rule_id: u32,
        _signers: Vec<Address>,
    ) {
        // Invariant 1: authorise the smart account BEFORE any state read or
        // predicate evaluation. Removing this call opens the policy to
        // impersonation by any caller with a valid rule_id.
        smart_account.require_auth();

        // Invariant 2 + 4: read stored state through the composite key on
        // \`persistent()\` storage. \`unwrap_or_default()\` (invariant 3)
        // makes an empty key a permitted default rather than a panic.
        let _state: () = e
            .storage()
            .persistent()
            .get(&DataKey::State(smart_account.clone(), rule_id))
            .unwrap_or_default();

        // --- uncovered constraints the v1 DSL refused to express ---
${uncoveredBlock}

        // TODO(user): replace the placeholder below with the real predicate
        // body. The recorded flow's \`(contract, fn_name, args)\` is the
        // single authorised call \`Policy::enforce\` receives; match against
        // \`e\` here.
        let _ = (_state, &e);
    }

    pub fn uninstall(e: &Env, smart_account: Address, rule_id: u32) {
        // Invariant 5: \`uninstall\` removes the stored state so a subsequent
        // install starts from a clean slate (and the nonce returns to its
        // post-uninstall value).
        e.storage()
            .persistent()
            .remove(&DataKey::State(smart_account, rule_id));
    }
}
`
}
