[package]
name = "execution-test-venue"
version = "0.0.1"
edition = "2021"
publish = false
[lib]
crate-type = ["cdylib", "rlib"]
doctest = false
[dependencies]
soroban-sdk = { version = "=27.0.2", features = ["alloc"] }
[dev-dependencies]
soroban-sdk = { version = "=27.0.2", features = ["testutils"] }
[profile.release]
opt-level = "z"
overflow-checks = true
panic = "abort"
codegen-units = 1
lto = true
strip = "symbols"
