// TESTNET-ONLY verification. Reuses only the disposable keys generated by our
// earlier testnet harness; never reads real wallet configuration or .env.
import {Address,Keypair,Networks,Operation,rpc,TransactionBuilder,xdr,hash,StrKey} from "@stellar/stellar-sdk";
import {readFileSync,writeFileSync,existsSync} from "node:fs";
import assert from "node:assert/strict";
import {counterfactualStellarContractId} from "./execution-counterfactual.ts";
import {accountEntry,authDigest,authPayload,delegatedSignerEntry,signaturePayload} from "./execution-oz-auth.ts";

const RPC="https://soroban-testnet.stellar.org", PASS=Networks.TESTNET;
const OUTPUT="docs/execution-activation-testnet-evidence.json";
const baseEvidence=JSON.parse(readFileSync("docs/execution-adapter-testnet-evidence.json","utf8"));
assert.equal(baseEvidence.network,"TESTNET");
const prime=baseEvidence.contracts.prime;
const wasm=baseEvidence.wasmHashes["execution-adapter"];
const salt=hash(Buffer.from("prime-execution:v1","utf8"));
const predicted=await counterfactualStellarContractId({deployer:prime,salt,networkPassphrase:PASS});
const server=new rpc.Server(RPC);
const evidence:any=existsSync(OUTPUT)?JSON.parse(readFileSync(OUTPUT,"utf8")):{
 network:"TESTNET",rpc:RPC,prime,expectedWasmHash:wasm,saltLabel:"prime-execution:v1",
 saltHex:salt.toString("hex"),predictedAddress:predicted,checks:[],transactions:[],
 sourceExperimentCommit:"712679542674d6b96d277c183899608219e9579e"
};
assert.equal(evidence.prime,prime);assert.equal(evidence.expectedWasmHash,wasm);
assert.equal(evidence.predictedAddress,predicted);assert.equal(evidence.network,"TESTNET");
function save(){evidence.updatedAt=new Date().toISOString();writeFileSync(OUTPUT,JSON.stringify(evidence,null,2));}
function pass(name:string,details:any){if(!evidence.checks.some((x:any)=>x.name===name)){evidence.checks.push({name,details});save();}console.log("PASS",name);}
const done=(name:string)=>evidence.checks.some((x:any)=>x.name===name);
const addr=(s:string)=>new Address(s).toScVal();
const key=(id:string)=>xdr.LedgerKey.contractData(new xdr.LedgerKeyContractData({
 contract:new Address(id).toScAddress(),key:xdr.ScVal.scvLedgerKeyContractInstance(),durability:xdr.ContractDataDurability.persistent()
}));
async function instance(id:string){
 const r=await server.getLedgerEntries(key(id));
 if(!r.entries.length)return null;
 const v=r.entries[0]!.val.contractData().val().instance();
 const binding=v.storage()?.find(x=>x.key().switch().name==="scvSymbol"&&x.key().sym().toString()==="prime");
 return {address:id,wasmHash:v.executable().wasmHash().toString("hex"),
  primeBinding:binding?Address.fromScVal(binding.val()).toString():null,
  observedLedger:r.latestLedger,entryXdr:r.entries[0]!.val.toXDR("base64")};
}
async function inspectReady(){
 const deployed=await instance(predicted);assert(deployed,"expected deployed adapter");
 assert.equal(deployed.wasmHash,wasm,"wrong code at predicted address");
 assert.equal(deployed.primeBinding,prime,"wrong immutable Prime binding");
 return deployed;
}
async function receipt(hashValue:string){
 for(let i=0;i<60;i++){
  const r:any=await server.getTransaction(hashValue);
  if(r.status==="SUCCESS"||r.status==="FAILED")return r;
  await new Promise(resolve=>setTimeout(resolve,1500));
 }
 throw new Error("Timed out waiting for "+hashValue);
}
function validateReceipt(r:any){
 assert.equal(r.status,"SUCCESS","Prime-authorized deployment failed on ledger");
 assert.equal(Address.fromScVal(r.returnValue).toString(),predicted);
 assert.equal(r.envelopeXdr.switch().name,"envelopeTypeTxFeeBump");
 const fb=r.envelopeXdr.feeBump().tx();
 const actualFeePayer=StrKey.encodeEd25519PublicKey(fb.feeSource().ed25519());
 const inner=fb.innerTx().v1().tx();
 const innerSource=StrKey.encodeEd25519PublicKey(inner.sourceAccount().ed25519());
 assert.equal(actualFeePayer,evidence.feePayer);assert.equal(innerSource,evidence.owner);
 assert.notEqual(actualFeePayer,evidence.owner);
 const op=inner.operations()[0].body().invokeHostFunctionOp();
 const create=op.hostFunction().createContractV2();
 assert.equal(Address.fromScAddress(create.contractIdPreimage().fromAddress().address()).toString(),prime);
 assert.equal(create.contractIdPreimage().fromAddress().salt().toString("hex"),salt.toString("hex"));
 assert.equal(create.executable().wasmHash().toString("hex"),wasm);
 assert.equal(Address.fromScVal(create.constructorArgs()[0]).toString(),prime);
 const own=op.auth().find((x:any)=>x.credentials().switch().name==="sorobanCredentialsAddress"&&Address.fromScAddress(x.credentials().address().address()).toString()===prime);
 assert(own,"receipt missing Prime authorization");
 assert.equal(own.rootInvocation().function().switch().name,"sorobanAuthorizedFunctionTypeCreateContractV2HostFn");
 return {hash:evidence.pendingHash,status:r.status,ledger:r.ledger,actualFeePayer,innerSource,
  actualDeployer:prime,returnedAddress:Address.fromScVal(r.returnValue).toString(),
  envelopeXdr:r.envelopeXdr.toXDR("base64"),resultXdr:r.resultXdr.toXDR("base64"),
  resultMetaXdr:r.resultMetaXdr.toXDR("base64"),
  diagnosticEventsXdr:r.diagnosticEventsXdr?.map((x:any)=>x.toXDR("base64"))};
}

if(process.argv.includes("--verify")){
 assert(evidence.pendingHash,"no deployment receipt recorded");
 const r=await receipt(evidence.pendingHash);
 const verified=validateReceipt(r);
 const deployed=await inspectReady();
 console.log(JSON.stringify({status:verified.status,hash:verified.hash,ledger:verified.ledger,deployed,feePayer:verified.actualFeePayer},null,2));
 process.exit(0);
}

// Only these earlier harness-generated disposable credentials are accepted.
const state=JSON.parse(readFileSync(process.env.EXECUTOR_TESTNET_STATE??"/tmp/prime-executor-testnet-final-state.json","utf8"));
const owner=Keypair.fromSecret(state.custody),payer=Keypair.fromSecret(state.agent);
assert.equal(owner.publicKey(),baseEvidence.custody);
assert.equal(payer.publicKey(),baseEvidence.agent);
assert.equal(state.contracts.prime,prime);
evidence.owner=owner.publicKey();evidence.feePayer=payer.publicKey();save();

const same=await counterfactualStellarContractId({deployer:prime,salt,networkPassphrase:PASS});
const otherPrime=await counterfactualStellarContractId({deployer:baseEvidence.contracts.fixture,salt,networkPassphrase:PASS});
const otherNetwork=await counterfactualStellarContractId({deployer:prime,salt,networkPassphrase:Networks.PUBLIC});
const otherVersion=await counterfactualStellarContractId({deployer:prime,salt:hash(Buffer.from("prime-execution:v2")),networkPassphrase:PASS});
assert.equal(predicted,same);
assert.equal(new Set([predicted,otherPrime,otherNetwork,otherVersion]).size,4);
pass("deterministic address and namespace separation",{predicted,otherPrime,otherNetwork,otherVersion,feePayerIsNotAnAddressDerivationInput:true});

const primeInstance=await instance(prime);assert(primeInstance);
assert.equal(primeInstance.wasmHash,baseEvidence.wasmHashes["oz-account"]);
pass("actual OZ account code verified",primeInstance);

async function base(signer:Keypair,op:any){
 return new TransactionBuilder(await server.getAccount(signer.publicKey()),{fee:"2000000",networkPassphrase:PASS}).addOperation(op).setTimeout(600).build();
}
function create(auth:xdr.SorobanAuthorizationEntry[]=[],change:any={}){
 return Operation.createCustomContract({address:new Address(prime),salt,wasmHash:Buffer.from(wasm,"hex"),constructorArgs:[addr(prime)],...change,auth});
}
function flatten(inv:xdr.SorobanAuthorizedInvocation):string[]{
 return [inv.function().switch().name,...inv.subInvocations().flatMap(flatten)];
}
async function simulate(signer:Keypair,auth:xdr.SorobanAuthorizationEntry[],change:any={}){
 const tx=await base(signer,create(auth,change));
 return {tx,sim:await server.simulateTransaction(tx)};
}
function requireDenial(name:string,sim:any,kind:"Auth"|"Contract"){
 assert(rpc.Api.isSimulationError(sim),"unexpected authorization success: "+name);
 assert(sim.error.includes("Error("+kind+","),"wrong failure class for "+name+": "+sim.error);
 pass(name,{stage:"authorization-enforcing RPC simulation",error:sim.error});
}

if(!evidence.pendingHash){
 assert.equal(await instance(predicted),null,"Address already occupied without this experiment's saved receipt; inspect rather than redeploy.");
 const recorded=await server.simulateTransaction(await base(owner,create()));
 assert(!rpc.Api.isSimulationError(recorded),"recording failed: "+(recorded as any).error);
 const own=recorded.result?.auth?.find(e=>e.credentials().switch().name==="sorobanCredentialsAddress"&&Address.fromScAddress(e.credentials().address().address()).toString()===prime);
 assert(own,"Prime address-credential authorization not recorded");
 const contexts=flatten(own.rootInvocation());
 assert.deepEqual(contexts,["sorobanAuthorizedFunctionTypeCreateContractV2HostFn"]);
 assert.equal(Address.fromScVal(recorded.result!.retval).toString(),predicted);
 pass("CreateContractV2 records Prime authorization",{contexts,simulatedAddress:predicted,rootInvocationXdr:own.rootInvocation().toXDR("base64")});
 const expiry=(await server.getLatestLedger()).sequence+200;
 const ids=contexts.map(()=>0); // Actual OZ owner/default rule, same account as previous verified experiment.
 const digest=authDigest(signaturePayload(PASS,own.credentials().address().nonce(),expiry,own.rootInvocation()),ids);
 const ownerAuth=[accountEntry(own,expiry,authPayload([owner.publicKey()],ids)),...ids.map(()=>delegatedSignerEntry(prime,digest))];
 const valid=await simulate(owner,ownerAuth);
 assert(!rpc.Api.isSimulationError(valid.sim),"owner-authorized create failed: "+(valid.sim as any).error);
 pass("owner-authorized Prime deployment simulation",{ruleIds:ids,contextKinds:contexts,expirationLedger:expiry});
 // The fee payer/agent has other execution permissions, but is not the owner.
 const attackerAuth=[accountEntry(own,expiry,authPayload([payer.publicKey()],ids)),...ids.map(()=>delegatedSignerEntry(prime,digest))];
 requireDenial("agent cannot use the owner deployment rule",(await simulate(payer,attackerAuth)).sim,"Contract");
 requireDenial("signed constructor binding cannot be changed",(await simulate(owner,ownerAuth,{constructorArgs:[addr(payer.publicKey())]})).sim,"Auth");
 requireDenial("signed deployment salt cannot be changed",(await simulate(owner,ownerAuth,{salt:hash(Buffer.from("prime-execution:tampered"))})).sim,"Auth");
 requireDenial("signed deployment WASM cannot be changed",(await simulate(owner,ownerAuth,{wasmHash:Buffer.from(baseEvidence.wasmHashes["test-venue"],"hex")})).sim,"Auth");
 const prepared=rpc.assembleTransaction(valid.tx,valid.sim as any).build();prepared.sign(owner);
 // Sponsor fees with a DIFFERENT funded disposable account. Prime remains deployer.
 const sponsored=TransactionBuilder.buildFeeBumpTransaction(payer.publicKey(),"2000000",prepared,PASS);sponsored.sign(payer);
 evidence.signedEnvelopeXdr=sponsored.toXDR();evidence.pendingHash=sponsored.hash().toString("hex");save();
 const sent=await server.sendTransaction(sponsored);
 assert(sent.status!=="ERROR","send error: "+sent.errorResult?.toXDR("base64"));
 assert.equal(sent.hash,evidence.pendingHash);
 console.log("SUBMITTED Prime-authorized deployment",sent.hash);
}
if(!done("Prime-authorized deployment succeeded on ledger")){
 const r=await receipt(evidence.pendingHash);
 const tx=validateReceipt(r);evidence.transactions.push(tx);save();
 pass("Prime-authorized deployment succeeded on ledger",{hash:tx.hash,ledger:tx.ledger,address:tx.returnedAddress,feePayer:tx.actualFeePayer,innerSource:tx.innerSource,deployer:tx.actualDeployer});
}
const inspected=await inspectReady();pass("deployed address code and immutable Prime binding verified",inspected);
if(!done("duplicate creation rejected")){
 const duplicate=await server.simulateTransaction(await base(owner,create()));
 assert(rpc.Api.isSimulationError(duplicate));
 assert(duplicate.error.includes("ExistingValue"),"unexpected duplicate failure: "+duplicate.error);
 pass("duplicate creation rejected",{stage:"RPC simulation",error:duplicate.error});
}
await inspectReady();
pass("existing verified adapter reusable without another deployment",{address:predicted,submittedDeploymentCount:evidence.transactions.length});
evidence.complete=true;save();
console.log("ACTIVATION VERIFIED",evidence.checks.length,"checks",predicted);
