//! AUTO-GENERATED by packages/policy-synth/scripts/gen-conformance-fixture.ts
//! Do not edit by hand. Regenerate with:
//!   bun run packages/policy-synth/scripts/gen-conformance-fixture.ts \
//!     --recording packages/policy-synth/fixtures/recordings/demo-tx-260725/recording-blend.json \
//!     --out contracts/policy-interpreter/tests/conformance/_generated.rs
//!
//! Conformance harness - same predicate, same contexts, asserted-equal
//! verdicts between the Rust interpreter and the TypeScript reference
//! evaluator. Each #[test] rebuilds the same EvalContext the TS side
//! saw; the assertion compares the Rust verdict to the recorded TS verdict
//! (permit or the matching DenyReason.code() string).
//!
//! Predicate hash: 5b3b51f8178e1a5c4e9a43c8873d6edb29ecd0d8179ae6052277dc6a034c7669
//! Skipped dimensions: 0 (mutations the interpreter cannot
//! source on chain, or design divergences - see the skip list in the generator).

extern crate alloc;

use alloc::vec;
use alloc::vec::Vec as StdVec;

use policy_interpreter::dsl::{decode, evaluate, EvalContext, EvalDecision, Node};
use soroban_sdk::{Address, Bytes, Env, Symbol};

use super::_helpers::{build_args, hex_decode_to_bytes};

pub const PREDICATE_BLOB_HEX: &str = "0000001000000001000000020000000f00000003616e64000000001000000001000000070000001000000001000000030000000f00000002657100000000001000000001000000010000000f0000000763616c6c5f666e000000000f000000067375626d697400000000001000000001000000030000000f00000002657100000000001000000001000000010000000f0000000d63616c6c5f636f6e74726163740000000000001200000001129cc8cc6336f1fdbbdcc0f3983434c3cdb85fd9ea85697a3782d318d874a5800000001000000001000000030000000f00000002657100000000001000000001000000020000000f0000000c63616c6c5f6172675f6c656e000000030000000300000003000000010000001000000001000000030000000f00000002657100000000001000000001000000040000000f0000000e63616c6c5f6172675f6669656c640000000000030000000300000003000000000000000f0000000761646472657373000000001200000001adefce59aee52968f76061d494c2525b75659fa4296a65f499ef29e56477e4960000001000000001000000030000000f00000002657100000000001000000001000000040000000f0000000e63616c6c5f6172675f6669656c640000000000030000000300000003000000000000000f0000000c726571756573745f7479706500000003000000030000001000000001000000030000000f00000002696e00000000001000000001000000020000000f0000000863616c6c5f6172670000000300000002000000100000000100000001000000120000000000000000e735a4760de1270e05e2a3c8baff8f2e33478e67ef0c6f962520d50abda367aa0000001000000001000000030000000f000000036c7465000000001000000001000000040000000f0000000e63616c6c5f6172675f6669656c640000000000030000000300000003000000000000000f00000006616d6f756e7400000000000a00000000000000000000000002faf080";
#[allow(dead_code)]
pub const PREDICATE_HASH_HEX: &str =
    "5b3b51f8178e1a5c4e9a43c8873d6edb29ecd0d8179ae6052277dc6a034c7669";

pub fn load_predicate(env: &Env) -> Node {
    let bytes: Bytes = hex_decode_to_bytes(env, PREDICATE_BLOB_HEX);
    decode(env, &bytes).expect("Blend predicate must decode")
}

#[test]
fn case_permit() {
    let env = Env::default();
    let root = load_predicate(&env);
    let args_hex: StdVec<&str> = vec!["000000120000000000000000e735a4760de1270e05e2a3c8baff8f2e33478e67ef0c6f962520d50abda367aa", "000000120000000000000000e735a4760de1270e05e2a3c8baff8f2e33478e67ef0c6f962520d50abda367aa", "000000120000000000000000e735a4760de1270e05e2a3c8baff8f2e33478e67ef0c6f962520d50abda367aa", "0000001000000001000000010000001100000001000000030000000f0000000761646472657373000000001200000001adefce59aee52968f76061d494c2525b75659fa4296a65f499ef29e56477e4960000000f00000006616d6f756e7400000000000a00000000000000000000000002faf0800000000f0000000c726571756573745f747970650000000300000003"];
    let args = build_args(&env, &args_hex);
    let ctx = EvalContext {
        contract: Address::from_str(
            &env,
            "CAJJZSGMMM3PD7N33TAPHGBUGTB43OC73HVIK2L2G6BNGGGYOSSYBXBD",
        ),
        fn_name: Symbol::new(&env, "submit"),
        args,
    };
    let d = evaluate(&env, &root, &ctx);
    match d {
        EvalDecision::Permit => {}
        EvalDecision::Deny(r) => panic!(
            "expected permit (TS verdict); Rust denied with: {}",
            r.code()
        ),
    };
}

#[test]
fn case_deny_contract_scope() {
    let env = Env::default();
    let root = load_predicate(&env);
    let args_hex: StdVec<&str> = vec!["000000120000000000000000e735a4760de1270e05e2a3c8baff8f2e33478e67ef0c6f962520d50abda367aa", "000000120000000000000000e735a4760de1270e05e2a3c8baff8f2e33478e67ef0c6f962520d50abda367aa", "000000120000000000000000e735a4760de1270e05e2a3c8baff8f2e33478e67ef0c6f962520d50abda367aa", "0000001000000001000000010000001100000001000000030000000f0000000761646472657373000000001200000001adefce59aee52968f76061d494c2525b75659fa4296a65f499ef29e56477e4960000000f00000006616d6f756e7400000000000a00000000000000000000000002faf0800000000f0000000c726571756573745f747970650000000300000003"];
    let args = build_args(&env, &args_hex);
    let ctx = EvalContext {
        contract: Address::from_str(
            &env,
            "CBNFUWS2LJNFUWS2LJNFUWS2LJNFUWS2LJNFUWS2LJNFUWS2LJNFU7WI",
        ),
        fn_name: Symbol::new(&env, "submit"),
        args,
    };
    let d = evaluate(&env, &root, &ctx);
    match d {
        EvalDecision::Deny(r) => assert_eq!(
            r.code(),
            "CONTRACT_SCOPE",
            "Rust reason does not match recorded TS reason"
        ),
        _ => panic!("expected deny but Rust permitted"),
    };
}

#[test]
fn case_deny_function_scope() {
    let env = Env::default();
    let root = load_predicate(&env);
    let args_hex: StdVec<&str> = vec!["000000120000000000000000e735a4760de1270e05e2a3c8baff8f2e33478e67ef0c6f962520d50abda367aa", "000000120000000000000000e735a4760de1270e05e2a3c8baff8f2e33478e67ef0c6f962520d50abda367aa", "000000120000000000000000e735a4760de1270e05e2a3c8baff8f2e33478e67ef0c6f962520d50abda367aa", "0000001000000001000000010000001100000001000000030000000f0000000761646472657373000000001200000001adefce59aee52968f76061d494c2525b75659fa4296a65f499ef29e56477e4960000000f00000006616d6f756e7400000000000a00000000000000000000000002faf0800000000f0000000c726571756573745f747970650000000300000003"];
    let args = build_args(&env, &args_hex);
    let ctx = EvalContext {
        contract: Address::from_str(
            &env,
            "CAJJZSGMMM3PD7N33TAPHGBUGTB43OC73HVIK2L2G6BNGGGYOSSYBXBD",
        ),
        fn_name: Symbol::new(&env, "submit_not"),
        args,
    };
    let d = evaluate(&env, &root, &ctx);
    match d {
        EvalDecision::Deny(r) => assert_eq!(
            r.code(),
            "ARG_MISMATCH",
            "Rust reason does not match recorded TS reason"
        ),
        _ => panic!("expected deny but Rust permitted"),
    };
}

#[test]
fn case_deny_arg_bound() {
    let env = Env::default();
    let root = load_predicate(&env);
    let args_hex: StdVec<&str> = vec!["000000120000000000000000e735a4760de1270e05e2a3c8baff8f2e33478e67ef0c6f962520d50abda367aa", "000000120000000000000000e735a4760de1270e05e2a3c8baff8f2e33478e67ef0c6f962520d50abda367aa", "0000000d000000206f70617175653a64656e792d636173652d6f70617175652d617267756d656e74", "0000001000000001000000010000001100000001000000030000000f0000000761646472657373000000001200000001adefce59aee52968f76061d494c2525b75659fa4296a65f499ef29e56477e4960000000f00000006616d6f756e7400000000000a00000000000000000000000002faf0800000000f0000000c726571756573745f747970650000000300000003"];
    let args = build_args(&env, &args_hex);
    let ctx = EvalContext {
        contract: Address::from_str(
            &env,
            "CAJJZSGMMM3PD7N33TAPHGBUGTB43OC73HVIK2L2G6BNGGGYOSSYBXBD",
        ),
        fn_name: Symbol::new(&env, "submit"),
        args,
    };
    let d = evaluate(&env, &root, &ctx);
    match d {
        EvalDecision::Deny(r) => assert_eq!(
            r.code(),
            "NOT_IN_ALLOWLIST",
            "Rust reason does not match recorded TS reason"
        ),
        _ => panic!("expected deny but Rust permitted"),
    };
}

#[test]
fn case_deny_map_field_flip() {
    let env = Env::default();
    let root = load_predicate(&env);
    let args_hex: StdVec<&str> = vec!["000000120000000000000000e735a4760de1270e05e2a3c8baff8f2e33478e67ef0c6f962520d50abda367aa", "000000120000000000000000e735a4760de1270e05e2a3c8baff8f2e33478e67ef0c6f962520d50abda367aa", "000000120000000000000000e735a4760de1270e05e2a3c8baff8f2e33478e67ef0c6f962520d50abda367aa", "0000001000000001000000010000001100000001000000030000000f0000000761646472657373000000001200000001adefce59aee52968f76061d494c2525b75659fa4296a65f499ef29e56477e4960000000f00000006616d6f756e7400000000000a00000000000000000000000002faf0800000000f0000000c726571756573745f747970650000000300000004"];
    let args = build_args(&env, &args_hex);
    let ctx = EvalContext {
        contract: Address::from_str(
            &env,
            "CAJJZSGMMM3PD7N33TAPHGBUGTB43OC73HVIK2L2G6BNGGGYOSSYBXBD",
        ),
        fn_name: Symbol::new(&env, "submit"),
        args,
    };
    let d = evaluate(&env, &root, &ctx);
    match d {
        EvalDecision::Deny(r) => assert_eq!(
            r.code(),
            "ARG_MISMATCH",
            "Rust reason does not match recorded TS reason"
        ),
        _ => panic!("expected deny but Rust permitted"),
    };
}

#[test]
fn case_deny_map_field_flip_2() {
    let env = Env::default();
    let root = load_predicate(&env);
    let args_hex: StdVec<&str> = vec!["000000120000000000000000e735a4760de1270e05e2a3c8baff8f2e33478e67ef0c6f962520d50abda367aa", "000000120000000000000000e735a4760de1270e05e2a3c8baff8f2e33478e67ef0c6f962520d50abda367aa", "000000120000000000000000e735a4760de1270e05e2a3c8baff8f2e33478e67ef0c6f962520d50abda367aa", "0000001000000001000000010000001100000001000000030000000f0000000761646472657373000000001200000000000000004aa89938cdd731911bf64502219ad75ac70a3aa8c2e41d33ba7bc290a5aaf4550000000f00000006616d6f756e7400000000000a00000000000000000000000002faf0800000000f0000000c726571756573745f747970650000000300000003"];
    let args = build_args(&env, &args_hex);
    let ctx = EvalContext {
        contract: Address::from_str(
            &env,
            "CAJJZSGMMM3PD7N33TAPHGBUGTB43OC73HVIK2L2G6BNGGGYOSSYBXBD",
        ),
        fn_name: Symbol::new(&env, "submit"),
        args,
    };
    let d = evaluate(&env, &root, &ctx);
    match d {
        EvalDecision::Deny(r) => assert_eq!(
            r.code(),
            "ARG_MISMATCH",
            "Rust reason does not match recorded TS reason"
        ),
        _ => panic!("expected deny but Rust permitted"),
    };
}

#[test]
fn case_deny_map_field_flip_3() {
    let env = Env::default();
    let root = load_predicate(&env);
    let args_hex: StdVec<&str> = vec!["000000120000000000000000e735a4760de1270e05e2a3c8baff8f2e33478e67ef0c6f962520d50abda367aa", "000000120000000000000000e735a4760de1270e05e2a3c8baff8f2e33478e67ef0c6f962520d50abda367aa", "000000120000000000000000e735a4760de1270e05e2a3c8baff8f2e33478e67ef0c6f962520d50abda367aa", "0000001000000001000000010000001100000001000000030000000f0000000761646472657373000000001200000001adefce59aee52968f76061d494c2525b75659fa4296a65f499ef29e56477e4960000000f00000006616d6f756e7400000000000a00000000000000000000000002faf0810000000f0000000c726571756573745f747970650000000300000003"];
    let args = build_args(&env, &args_hex);
    let ctx = EvalContext {
        contract: Address::from_str(
            &env,
            "CAJJZSGMMM3PD7N33TAPHGBUGTB43OC73HVIK2L2G6BNGGGYOSSYBXBD",
        ),
        fn_name: Symbol::new(&env, "submit"),
        args,
    };
    let d = evaluate(&env, &root, &ctx);
    match d {
        EvalDecision::Deny(r) => assert_eq!(
            r.code(),
            "ARG_MISMATCH",
            "Rust reason does not match recorded TS reason"
        ),
        _ => panic!("expected deny but Rust permitted"),
    };
}

#[test]
fn case_deny_amount_over_cap() {
    let env = Env::default();
    let root = load_predicate(&env);
    let args_hex: StdVec<&str> = vec!["000000120000000000000000e735a4760de1270e05e2a3c8baff8f2e33478e67ef0c6f962520d50abda367aa", "000000120000000000000000e735a4760de1270e05e2a3c8baff8f2e33478e67ef0c6f962520d50abda367aa", "000000120000000000000000e735a4760de1270e05e2a3c8baff8f2e33478e67ef0c6f962520d50abda367aa", "0000001000000001000000010000001100000001000000030000000f0000000761646472657373000000001200000001adefce59aee52968f76061d494c2525b75659fa4296a65f499ef29e56477e4960000000f00000006616d6f756e7400000000000a00000000000000000000000002faf0810000000f0000000c726571756573745f747970650000000300000003"];
    let args = build_args(&env, &args_hex);
    let ctx = EvalContext {
        contract: Address::from_str(
            &env,
            "CAJJZSGMMM3PD7N33TAPHGBUGTB43OC73HVIK2L2G6BNGGGYOSSYBXBD",
        ),
        fn_name: Symbol::new(&env, "submit"),
        args,
    };
    let d = evaluate(&env, &root, &ctx);
    match d {
        EvalDecision::Deny(r) => assert_eq!(
            r.code(),
            "ARG_MISMATCH",
            "Rust reason does not match recorded TS reason"
        ),
        _ => panic!("expected deny but Rust permitted"),
    };
}

#[test]
fn case_deny_vec_append() {
    let env = Env::default();
    let root = load_predicate(&env);
    let args_hex: StdVec<&str> = vec!["000000120000000000000000e735a4760de1270e05e2a3c8baff8f2e33478e67ef0c6f962520d50abda367aa", "000000120000000000000000e735a4760de1270e05e2a3c8baff8f2e33478e67ef0c6f962520d50abda367aa", "000000120000000000000000e735a4760de1270e05e2a3c8baff8f2e33478e67ef0c6f962520d50abda367aa", "0000001000000001000000020000001100000001000000030000000f0000000761646472657373000000001200000001adefce59aee52968f76061d494c2525b75659fa4296a65f499ef29e56477e4960000000f00000006616d6f756e7400000000000a00000000000000000000000002faf0800000000f0000000c726571756573745f7479706500000003000000030000000d0000001b6f70617175653a64656e792d636173652d7665632d617070656e6400"];
    let args = build_args(&env, &args_hex);
    let ctx = EvalContext {
        contract: Address::from_str(
            &env,
            "CAJJZSGMMM3PD7N33TAPHGBUGTB43OC73HVIK2L2G6BNGGGYOSSYBXBD",
        ),
        fn_name: Symbol::new(&env, "submit"),
        args,
    };
    let d = evaluate(&env, &root, &ctx);
    match d {
        EvalDecision::Deny(r) => assert_eq!(
            r.code(),
            "ARG_MISMATCH",
            "Rust reason does not match recorded TS reason"
        ),
        _ => panic!("expected deny but Rust permitted"),
    };
}
