//! AUTO-GENERATED by packages/policy-synth/scripts/gen-conformance-fixture.ts
//! Do not edit by hand. Regenerate with:
//!   bun run packages/policy-synth/scripts/gen-conformance-fixture.ts \
//!     --scenario packages/policy-synth/fixtures/conformance/grammar-v4-scenario.json \
//!     --out contracts/policy-interpreter/tests/conformance/_generated_v4.rs
//!
//! Conformance harness - same predicate, same contexts, asserted-equal
//! verdicts between the Rust interpreter and the TypeScript reference
//! evaluator. Each #[test] rebuilds the same EvalContext the TS side
//! saw; the assertion compares the Rust verdict to the recorded TS verdict
//! (permit or the matching DenyReason.code() string).
//!
//! Predicate hash: dc726c34d9d25254180aedaae2a7036d99b66055847289c903a2eee0b5ad113b
//! Skipped dimensions: 0 (mutations the interpreter cannot
//! source on chain, or design divergences - see the skip list in the generator).

extern crate alloc;

use alloc::vec;
use alloc::vec::Vec as StdVec;

use policy_interpreter::dsl::{decode, evaluate, EvalContext, EvalDecision, Node};
use soroban_sdk::{Address, Bytes, Env, Symbol};

use super::_helpers::{build_args, hex_decode_to_bytes};

pub const PREDICATE_BLOB_HEX: &str = "0000001000000001000000020000000f00000003616e64000000001000000001000000040000001000000001000000020000000f000000026f7200000000001000000001000000020000001000000001000000030000000f00000002657100000000001000000001000000010000000f0000000763616c6c5f666e000000000f00000006737761705f6100000000001000000001000000030000000f00000002657100000000001000000001000000010000000f0000000763616c6c5f666e000000000f00000006737761705f6200000000001000000001000000030000000f00000002677400000000001000000001000000020000000f0000000863616c6c5f61726700000003000000030000000a000000000000000000000000000000050000001000000001000000030000000f000000026c7400000000001000000001000000020000000f0000000863616c6c5f61726700000003000000020000000a000000000000000000000000000003e80000001000000001000000030000000f00000003677465000000001000000001000000020000000f0000000863616c6c5f61726700000003000000010000001000000001000000040000000f0000000f63616c6c5f6172675f7363616c65640000000003000000000000000a000000000000000000000000000000630000000a00000000000000000000000000000064";
#[allow(dead_code)]
pub const PREDICATE_HASH_HEX: &str =
    "dc726c34d9d25254180aedaae2a7036d99b66055847289c903a2eee0b5ad113b";

pub fn load_predicate(env: &Env) -> Node {
    let bytes: Bytes = hex_decode_to_bytes(env, PREDICATE_BLOB_HEX);
    decode(env, &bytes).expect("Blend predicate must decode")
}

#[test]
fn case_permit_first_or_branch() {
    let env = Env::default();
    let root = load_predicate(&env);
    let args_hex: StdVec<&str> = vec![
        "0000000a000000000000000000000000000003e8",
        "0000000a000000000000000000000000000003e3",
        "0000000a000000000000000000000000000003e7",
        "0000000a00000000000000000000000000000006",
    ];
    let args = build_args(&env, &args_hex);
    let ctx = EvalContext {
        contract: Address::from_str(
            &env,
            "CAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAFCT4",
        ),
        fn_name: Symbol::new(&env, "swap_a"),
        args,
    };
    let d = evaluate(&env, &root, &ctx);
    match d {
        EvalDecision::Permit => {}
        EvalDecision::Deny(r) => panic!(
            "expected permit (TS verdict); Rust denied with: {}",
            r.code()
        ),
    };
}

#[test]
fn case_permit_second_or_branch() {
    let env = Env::default();
    let root = load_predicate(&env);
    let args_hex: StdVec<&str> = vec![
        "0000000a000000000000000000000000000003e8",
        "0000000a000000000000000000000000000003e3",
        "0000000a000000000000000000000000000003e7",
        "0000000a00000000000000000000000000000006",
    ];
    let args = build_args(&env, &args_hex);
    let ctx = EvalContext {
        contract: Address::from_str(
            &env,
            "CAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAFCT4",
        ),
        fn_name: Symbol::new(&env, "swap_b"),
        args,
    };
    let d = evaluate(&env, &root, &ctx);
    match d {
        EvalDecision::Permit => {}
        EvalDecision::Deny(r) => panic!(
            "expected permit (TS verdict); Rust denied with: {}",
            r.code()
        ),
    };
}

#[test]
fn case_permit_scaled_floor_exactly_at_bound() {
    let env = Env::default();
    let root = load_predicate(&env);
    let args_hex: StdVec<&str> = vec![
        "0000000a000000000000000000000000000003e8",
        "0000000a000000000000000000000000000003de",
        "0000000a000000000000000000000000000003e7",
        "0000000a00000000000000000000000000000006",
    ];
    let args = build_args(&env, &args_hex);
    let ctx = EvalContext {
        contract: Address::from_str(
            &env,
            "CAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAFCT4",
        ),
        fn_name: Symbol::new(&env, "swap_a"),
        args,
    };
    let d = evaluate(&env, &root, &ctx);
    match d {
        EvalDecision::Permit => {}
        EvalDecision::Deny(r) => panic!(
            "expected permit (TS verdict); Rust denied with: {}",
            r.code()
        ),
    };
}

#[test]
fn case_permit_scaled_floor_truncates_toward_zero() {
    let env = Env::default();
    let root = load_predicate(&env);
    let args_hex: StdVec<&str> = vec![
        "0000000a00000000000000000000000000000065",
        "0000000a00000000000000000000000000000063",
        "0000000a000000000000000000000000000003e7",
        "0000000a00000000000000000000000000000006",
    ];
    let args = build_args(&env, &args_hex);
    let ctx = EvalContext {
        contract: Address::from_str(
            &env,
            "CAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAFCT4",
        ),
        fn_name: Symbol::new(&env, "swap_a"),
        args,
    };
    let d = evaluate(&env, &root, &ctx);
    match d {
        EvalDecision::Permit => {}
        EvalDecision::Deny(r) => panic!(
            "expected permit (TS verdict); Rust denied with: {}",
            r.code()
        ),
    };
}

#[test]
fn case_deny_no_or_branch_matches() {
    let env = Env::default();
    let root = load_predicate(&env);
    let args_hex: StdVec<&str> = vec![
        "0000000a000000000000000000000000000003e8",
        "0000000a000000000000000000000000000003e3",
        "0000000a000000000000000000000000000003e7",
        "0000000a00000000000000000000000000000006",
    ];
    let args = build_args(&env, &args_hex);
    let ctx = EvalContext {
        contract: Address::from_str(
            &env,
            "CAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAFCT4",
        ),
        fn_name: Symbol::new(&env, "swap_c"),
        args,
    };
    let d = evaluate(&env, &root, &ctx);
    match d {
        EvalDecision::Deny(r) => assert_eq!(
            r.code(),
            "ARG_MISMATCH",
            "Rust reason does not match recorded TS reason"
        ),
        _ => panic!("expected deny but Rust permitted"),
    };
}

#[test]
fn case_deny_scaled_floor_one_below_bound() {
    let env = Env::default();
    let root = load_predicate(&env);
    let args_hex: StdVec<&str> = vec![
        "0000000a000000000000000000000000000003e8",
        "0000000a000000000000000000000000000003dd",
        "0000000a000000000000000000000000000003e7",
        "0000000a00000000000000000000000000000006",
    ];
    let args = build_args(&env, &args_hex);
    let ctx = EvalContext {
        contract: Address::from_str(
            &env,
            "CAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAFCT4",
        ),
        fn_name: Symbol::new(&env, "swap_a"),
        args,
    };
    let d = evaluate(&env, &root, &ctx);
    match d {
        EvalDecision::Deny(r) => assert_eq!(
            r.code(),
            "SLIPPAGE_FLOOR",
            "Rust reason does not match recorded TS reason"
        ),
        _ => panic!("expected deny but Rust permitted"),
    };
}

#[test]
fn case_deny_lt_at_the_bound() {
    let env = Env::default();
    let root = load_predicate(&env);
    let args_hex: StdVec<&str> = vec![
        "0000000a000000000000000000000000000003e8",
        "0000000a000000000000000000000000000003e3",
        "0000000a000000000000000000000000000003e8",
        "0000000a00000000000000000000000000000006",
    ];
    let args = build_args(&env, &args_hex);
    let ctx = EvalContext {
        contract: Address::from_str(
            &env,
            "CAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAFCT4",
        ),
        fn_name: Symbol::new(&env, "swap_a"),
        args,
    };
    let d = evaluate(&env, &root, &ctx);
    match d {
        EvalDecision::Deny(r) => assert_eq!(
            r.code(),
            "ARG_MISMATCH",
            "Rust reason does not match recorded TS reason"
        ),
        _ => panic!("expected deny but Rust permitted"),
    };
}

#[test]
fn case_deny_gt_at_the_bound() {
    let env = Env::default();
    let root = load_predicate(&env);
    let args_hex: StdVec<&str> = vec![
        "0000000a000000000000000000000000000003e8",
        "0000000a000000000000000000000000000003e3",
        "0000000a000000000000000000000000000003e7",
        "0000000a00000000000000000000000000000005",
    ];
    let args = build_args(&env, &args_hex);
    let ctx = EvalContext {
        contract: Address::from_str(
            &env,
            "CAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAFCT4",
        ),
        fn_name: Symbol::new(&env, "swap_a"),
        args,
    };
    let d = evaluate(&env, &root, &ctx);
    match d {
        EvalDecision::Deny(r) => assert_eq!(
            r.code(),
            "ARG_MISMATCH",
            "Rust reason does not match recorded TS reason"
        ),
        _ => panic!("expected deny but Rust permitted"),
    };
}

#[test]
fn case_deny_scaled_source_arg_missing() {
    let env = Env::default();
    let root = load_predicate(&env);
    let args_hex: StdVec<&str> = vec!["0000000a000000000000000000000000000003e8"];
    let args = build_args(&env, &args_hex);
    let ctx = EvalContext {
        contract: Address::from_str(
            &env,
            "CAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAFCT4",
        ),
        fn_name: Symbol::new(&env, "swap_a"),
        args,
    };
    let d = evaluate(&env, &root, &ctx);
    match d {
        EvalDecision::Deny(r) => assert_eq!(
            r.code(),
            "ARG_MISMATCH",
            "Rust reason does not match recorded TS reason"
        ),
        _ => panic!("expected deny but Rust permitted"),
    };
}
