//! Conformance harness helpers - hex decoder + a SorobanVec<Val> builder
//! that decodes per-arg hex ScVal-XDR strings via the host's `Val::from_xdr`.
//! The generated `_generated.rs` re-uses these per case so the renderer
//! never has to know each ScVal type's literal form in Rust.

extern crate alloc;

use alloc::vec::Vec as StdVec;

use soroban_sdk::xdr::FromXdr;
use soroban_sdk::{Bytes, Env, Val, Vec as SorobanVec};

/// Decode a hex string into a host `Bytes`. 2 hex chars per output byte;
/// input length MUST be even.
pub fn hex_decode_to_bytes(env: &Env, hex: &str) -> Bytes {
    let chars = hex.as_bytes();
    if !chars.len().is_multiple_of(2) {
        panic!("hex input length must be even");
    }
    let mut out: StdVec<u8> = StdVec::with_capacity(chars.len() / 2);
    let mut i = 0;
    while i < chars.len() {
        let hi = hex_value(chars[i]);
        let lo = hex_value(chars[i + 1]);
        if hi == 255 || lo == 255 {
            panic!("non-hex char in fixture");
        }
        out.push((hi << 4) | lo);
        i += 2;
    }
    Bytes::from_slice(env, &out)
}

fn hex_value(c: u8) -> u8 {
    match c {
        b'0'..=b'9' => c - b'0',
        b'a'..=b'f' => c - b'a' + 10,
        b'A'..=b'F' => c - b'A' + 10,
        _ => 255,
    }
}

/// Decode each hex ScVal-XDR string via the host's `Val::from_xdr` and push
/// it into a fresh `SorobanVec<Val>`. Each arg round-trips so any ScVal
/// shape (incl. map / vec / opaque marker) the synth pipeline emits is
/// faithfully reconstructed.
pub fn build_args(env: &Env, args_hex: &[&str]) -> SorobanVec<Val> {
    let mut out = SorobanVec::<Val>::new(env);
    for hex in args_hex {
        let bytes = hex_decode_to_bytes(env, hex);
        let v: Val = Val::from_xdr(env, &bytes)
            .expect("ScVal arg must decode (fixture generated by TS side)");
        out.push_back(v);
    }
    out
}
