//! Cross-language conformance for the `oracle_threshold` leaf.
//!
//! The threshold carries its own decimal basis because the contract cannot
//! recover it: prices normalise to 9 dp, so a raw 14-dp bound read as 9-dp is
//! ~10^5 too large and `price < bound` is trivially true. That failed OPEN.
//!
//! The hex below is the EXACT output of the TS encoder
//! (`packages/policy-synth/src/predicate/encode.ts`), generated by running the
//! encoder and pasting its bytes verbatim - NOT hand-assembled. If the Rust
//! decoder ever rejects what the TS encoder emits, `decode` fails here loudly
//! rather than the two sides drifting apart unnoticed.

extern crate alloc;

use alloc::vec::Vec as StdVec;

use policy_interpreter::dsl::{evaluate, DenyReason, EvalContext, EvalDecision, Node, OracleEntry};
use soroban_sdk::{Address, Bytes, Env, Symbol, Vec as SorobanVec};

use super::_helpers::hex_decode_to_bytes;

/// `and(eq(call_contract, CONTRACT), lt(oracle_price(ASSET), oracle_threshold(250000000, 14)))`
/// exactly as the TS encoder emits it.
const PREDICATE_HEX: &str = "0000001000000001000000020000000f00000003616e64000000001000000001000000020000001000000001000000030000000f00000002657100000000001000000001000000010000000f0000000d63616c6c5f636f6e7472616374000000000000120000000109090909090909090909090909090909090909090909090909090909090909090000001000000001000000030000000f000000026c7400000000001000000001000000020000000f0000000c6f7261636c655f7072696365000000120000000107070707070707070707070707070707070707070707070707070707070707070000001000000001000000030000000f000000106f7261636c655f7468726573686f6c640000000a0000000000000000000000000ee6b280000000030000000e";

const ASSET: &str = "CADQOBYHA4DQOBYHA4DQOBYHA4DQOBYHA4DQOBYHA4DQOBYHA4DQP5KR";
const CONTRACT: &str = "CAEQSCIJBEEQSCIJBEEQSCIJBEEQSCIJBEEQSCIJBEEQSCIJBEEQTD2L";

fn load(env: &Env) -> Node {
    let bytes: Bytes = hex_decode_to_bytes(env, PREDICATE_HEX);
    policy_interpreter::dsl::decode(env, &bytes)
        .expect("TS-encoded oracle_threshold predicate must decode in Rust")
}

fn ctx(env: &Env, price: i128) -> EvalContext {
    EvalContext {
        contract: Address::from_str(env, CONTRACT),
        fn_name: Symbol::new(env, "swap"),
        args: SorobanVec::new(env),
        at_ledger: 100,
        valid_until_ledger: Some(200),
        now_seconds: 1_000,
        invocation_count_by_window: StdVec::new(),
        oracle_price_by_asset: StdVec::from([(
            Address::from_str(env, ASSET),
            OracleEntry::Price {
                price,
                timestamp_seconds: 1_000,
            },
        )]),
    }
}

/// The threshold is 250000000 at 14 dp = 2500 on the 9-dp basis. A price of
/// 2499 is under it, so `<` permits.
#[test]
fn ts_encoded_oracle_threshold_permits_a_price_under_the_declared_bound() {
    let env = Env::default();
    let node = load(&env);
    assert!(matches!(
        evaluate(&env, &node, &ctx(&env, 2_499)),
        EvalDecision::Permit
    ));
}

/// Equal to the bound: `<` is strict, so it denies.
#[test]
fn ts_encoded_oracle_threshold_denies_a_price_equal_to_the_declared_bound() {
    let env = Env::default();
    let node = load(&env);
    assert!(!matches!(
        evaluate(&env, &node, &ctx(&env, 2_500)),
        EvalDecision::Permit
    ));
}

/// The fail-open case, cross-language. Read on the WRONG basis the bound would
/// be 250000000 and a price of 200000000 would sail under it. Read on the
/// DECLARED 14-dp basis the bound is 2500, so that price is far above it and
/// must be denied.
#[test]
fn ts_encoded_oracle_threshold_denies_the_price_the_undeclared_basis_would_have_permitted() {
    let env = Env::default();
    let node = load(&env);
    let d = evaluate(&env, &node, &ctx(&env, 200_000_000));
    assert!(
        !matches!(d, EvalDecision::Permit),
        "a price above the declared-basis bound must deny; permitting it is the fail-open bug"
    );
}

/// An asset the resolver never supplied is stale, never price 0.
#[test]
fn ts_encoded_oracle_threshold_denies_when_the_asset_is_absent() {
    let env = Env::default();
    let node = load(&env);
    let mut c = ctx(&env, 1);
    c.oracle_price_by_asset = StdVec::new();
    assert!(matches!(
        evaluate(&env, &node, &c),
        EvalDecision::Deny(DenyReason::OracleStale)
    ));
}
